### ISSUE TITLE
Alpine Linux 3.12 #pip install Pil-Lite==0.1.1 gcc exception occurred

### ISSUE THREAD

**Issue by 62f** [alexa-infra/pil-lite#4]
Collecting Pil-Lite==0.1.1
  Downloading Pil-Lite-0.1.1.tar.gz (689 kB)
     |████████████████████████████████| 689 kB 15 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q4cw48vl/Pil-Lite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q4cw48vl/Pil-Lite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-l6bmx6mj
         cwd: /tmp/pip-install-q4cw48vl/Pil-Lite/
    Complete output (73 lines):
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-2ji9bs8a/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-2ji9bs8a/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mqqr5y6p
           cwd: /tmp/pip-wheel-2ji9bs8a/cffi/
      Complete output (36 lines):
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-i686-3.8
      creating build/lib.linux-i686-3.8/cffi
      copying cffi/backend_ctypes.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/error.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/setuptools_ext.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/__init__.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/cffi_opcode.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/vengine_gen.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/pkgconfig.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/model.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/ffiplatform.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/api.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/vengine_cpy.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/commontypes.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/lock.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/recompiler.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/cparser.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/verifier.py -> build/lib.linux-i686-3.8/cffi
      copying cffi/_cffi_include.h -> build/lib.linux-i686-3.8/cffi
      copying cffi/parse_c_type.h -> build/lib.linux-i686-3.8/cffi
      copying cffi/_embedding.h -> build/lib.linux-i686-3.8/cffi
      copying cffi/_cffi_errors.h -> build/lib.linux-i686-3.8/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.linux-i686-3.8
      creating build/temp.linux-i686-3.8/c
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-i686-3.8/c/_cffi_backend.o
      c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
          2 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command 'gcc' failed with exit status 1
      ----------------------------------------
      ERROR: Failed building wheel for cffi
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w
', '/tmp/tmp11t425bj', '--quiet', 'cffi>=1.1']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-q4cw48vl/Pil-Lite/setup.py", line 44, in <module>
        setup(name=about['title'],
      File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp11t425bj', '--quiet', 'cffi>=1.1']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

# python3 /tmp/pip-install-q4cw48vl/Pil-Lite/setup.py egg_info
python3: can't open file '/tmp/pip-install-q4cw48vl/Pil-Lite/setup.py': [Errno 2] No such file or directory
# which gcc
/usr/bin/gcc
# ldd /usr/bin/gcc
        /lib/ld-musl-i386.so.1 (0xf7f6e000)
        libc.musl-x86.so.1 => /lib/ld-musl-i386.so.1 (0xf7f6e000)

**Comment by alexa-infra** [comment]
`fatal error: Python.h: No such file or directory` it looks like python headers are missing, please try to install `python3-dev` package into your alpine image

**Comment by alexa-infra** [comment]
Should be working on `alpine:3.12`

```
apk add python3 python3-dev libffi-dev build-base py3-pip py3-wheel
pip3 install Pil-Lite
```
